### ISSUE TITLE
Exception raised when waiting for the new event.

### ISSUE THREAD

**Issue by ikasymov** [pyeventsourcing/esdbclient#15]
version = "1.0.10"

After updating the library version to later, I got this error, before that code was working correctly, I didn't touch anything.
To reproduce need to run the consumer via the management command. In a simply consumer without the django command also raised the error.

```
class Command(BaseCommand):
    help = "Run event store consumers"

    def handle(self, *args, **options) -> None:
        client = get_event_store_client()

        subscription = client.read_subscription_to_stream(
            group_name="my_group",
            stream_name="$ce-acquired_orders",
        )

        for event in subscription:
            # Acknowledge the received event.
            subscription.ack(event)
```

```
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/grpc/_channel.py", line 274, in consume_request_iterator
    request = next(request_iterator)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/esdbclient/persistent.py", line 514, in __next__
    event_id, action = self._ack_queue.get(timeout=get_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/queue.py", line 173, in get
    raise ValueError("'timeout' must be a non-negative number")
ValueError: 'timeout' must be a non-negative number
```

The error does not appear immediately after startup, but after some time.

**Comment by johnbywater** [comment]
Thanks for the report @ikasymov.

The code was changed in a previous version to be more punctual about sending acks on time. But it was using the system clock rather than a monotonic clock. And when the system clock drifts and is updated by NTP or something, it can go backwards. This resulted in a negative age for the batch, and then a negative timeout value for the queue.

I changed the code (9ed72cc9503e6e8ec9a58b70027d35c33eb90b3e) to use a monotonic clock to measure the age of the batch. After this change, the age of the batch, and hence the queue timeout value, should never be negative.

Please update to 1.0.11. Thanks again for your all great feedback.

**Comment by johnbywater** [comment]
@ikasymov actually, use 1.0.12 :-)
