### ISSUE TITLE
ValueError: root_certificates is required for secure connection

### ISSUE THREAD

**Issue by alexeyzimarev** [pyeventsourcing/esdbclient#18]
When connecting to ES Cloud cluster, the client produces this error:

```
ValueError: root_certificates is required for secure connection
```

This requirement _must not be there_ as root certificate is only required when connecting to a cluster or instance, which is using an untrusted certificate. Because ES Cloud is using certificates signed by a public CA, users don't even have access to the root certificate (no one does).

**Comment by johnbywater** [comment]
Alright, we can certainly relax this and see what happens.

You may or may not be aware that this client has never been tested with the ES Cloud service. This was discussed a few times with Yves but we didn't try to do this, due to there being some "awkwardness" in doing so. More than happy to work on this with you. Good to see it's been tried at least! Although one might have thought that it would, I'm totally not surprised that it didn't "just work" first time.

By the way, the "root certificate" is the root of the public certificate chain, ie the public certificate for the CA?

https://en.wikipedia.org/wiki/Root_certificate

These are widely distributed, probably installed on your machine? The argument is plural because there can be a number of different ones, hopefully one of which can be used to authenticate the server, by checking the server certificate has been signed by the CA, the signing having used undisclosed secrets, but then verifiable with its public certificate (in the usual way with PKI). I can imagine a grpc library could pick these up from locally installed certificates, I know the ssl library does, and I guess the the Python grpc library actually does this too, but I don't actually know for sure.

So let's relax this constraint that I coded into this package, and see if it works.

**Comment by alexeyzimarev** [comment]
Yeah, you're right, it must be there (the public part). It's just people normally don't know where it is :)

I believe just omitting all the code related to certificate validation and letting the default work should do the trick. It's not just ES Cloud, it applies to any deployment where people use trusted certs. They don't have to be signed by a public CA. There are environments where there's a private CA but it's trusted by default.

**Comment by johnbywater** [comment]
@alexeyzimarev Please upgrade to v1.0.13, try again to connect to secure server without specifying root certificates when constructing the client, ]see if the grpc library picks up local root certificates from the default location, and let me know what you find? I guess they also need to be installed for this to work. But it might also not work. There's some history in 2021 of this not working. There was a work around at that time to set the default location in an environment variable. But by now it might all just work. Please let me know what you find?

**Comment by johnbywater** [comment]
@alexeyzimarev does this work?
