### ISSUE TITLE
Add the created date time of the event

### ISSUE THREAD

**Issue by ikasymov** [pyeventsourcing/esdbclient#20]
Would be good to add the created date time of the event to RecordedEvent object. I see that EventStoreDB indicates the time for each event, but I cannot get them through RecordedEvent.

**Comment by johnbywater** [comment]
Thanks for raising the issue @ikasymov.

You are correct. There is a timestamp generated by the server, which is returned when events are read. But it's not part of the Protobuf spec. It's just a conventional value in the "metadata". Not the "custom metadata" which is what a user provided in the "metadata" argument to NewEvent, but the server's "metadata", which in the Protobuf spec is defined as a map of string keys and string values. In this map, the server-generated timestamp is labelled as "created", but it's actually the time the event was recorded. And AFAIK it's possible for this value to change, for example if the events are rerecorded (e.g. whenever you migrate data). So you can't rely on it as a value in your domain model. I don't know if that's what you are intending or not. Perhaps you want to know when the event was recorded on the server?

It would certainly be possible to present this value. But I don't know which type would be best. It comes back as a string, which represents an integer. You have to divide this number by 10,000,000 to get "the number of seconds since the epoch". So the number you get from the server represents the number of 100s of nano seconds since the epoch, I think.

Would it be most useful to present the string? to cast the string to an integer and leave people guessing about what the number represents? to divide by 10,000,000 and return a float leaving people to search for how to convert to a datetime object? to convert the float to a Python datetime object and lose some precision since date time objects only have microseconds? I simply don't know what would be best. What do you think?

To be honest, if you want a timestamp for when the event is created, I would add this to the metadata yourself. Then you will know when the event object was originally created, rather than when record was written by the server. I would say, if you care about when an event, then put it in your model. Give it a name that indicates what this time represents. There may be more than one time associated with an event. If you prefer to have a value for when the event object was created, and you want this as metadata, then add this yourself, perhaps by subclassing the NewEvent class?

Having said all that, I am willing to present the server-generated "created" timestamp. But I don't know which type to use. And also since "created" seems to me not a very great name for what this value actually represents, I would need to consider the name of the attribute on RecordedEvent a little bit too.

What do you think?

**Comment by johnbywater** [comment]
If you update to v1.0.20 there is a new attribute recorded_at. Hope that helps?
