### ISSUE TITLE
Is there any plans for JSONEvent?

### ISSUE THREAD

**Issue by goznauk** [pyeventsourcing/esdbclient#5]
I'm new to python, and I'm using this library for IPC calls to other non-python programs.
However, unexpectedly, the event published from this library can't be read as same as others published on [NodeJS client](https://github.com/EventStore/EventStore-Client-NodeJS).

After a while I encountered this problem, I'd changed `contentType` from `application/octet-stream` to `application/json` and [this kind of fix](
https://github.com/goznauk/esdbclient/commit/4539479b88392bfafb82f5de360f95087b748757) make it works anyway. I'm not good at eventstoreDB, but I guess this is related to event types, such as `JSONEventType` or `BinaryEventType` in node client.

I'm not sure but it seems `application/json` is more recommended way to publish.
Is there any reason to use `application/octet-stream`? or Do you have any plans for event type support?

**Comment by johnbywater** [comment]
Thanks for this suggestion. I like your code changes. I added a TODO for this here: https://github.com/pyeventsourcing/esdbclient/blob/1d1f72e74578356eebf227dcf9749842416762ff/TODOS.md?plain=1#L11

**Comment by johnbywater** [comment]
Hey @goznauk,

I have tried to resolve this issue by adjusting the `NewEvent` class so that is has a `content_type` attribute, which by default is `application/json` and which can alternatively take the value `application/octet-stream` if given as a constructor argument. 

The value of this attribute is used when proposing events to be appended in the database. The recorded value is then set as the `content_type` attribute of the `RecordedEvent` class when reading events from the database.

https://github.com/pyeventsourcing/esdbclient#the-newevent-class

Let me know what you think?

The `NewEvent` class now also has an `id` attribute, which by default will be a new version-4 UUID, and which can alternatively take a value given as a constructor argument. The value of this attribute is used when appending events. This effectively implements support in this client for the idempotent append operation supported by the server. Previously the event ID was generated within the append method, and so any retries would not use the same event ID.

I've also implemented support for SSL/TLS and username/password authentication, requires to connect to "secure" servers. And a few other smaller things, such as filtering on persistent subscriptions.

I've updated the README accordingly. Please check out v0.9, which is now available on PyPI, for which I remembered to add a tag! :-)

https://pypi.org/project/esdbclient/0.9/

**Comment by goznauk** [comment]
@johnbywater Thank you for nice library :) I'll update and try soon!
