### ISSUE TITLE
ACK on events in Persistent Subscription

### ISSUE THREAD

**Issue by lzukowski** [pyeventsourcing/esdbclient#8]
Hi.
I assumed that persistent subscription events that were ACK, should not be repeated to consumers anymore. But it appears that they are. [Here](https://github.com/lzukowski/esdbclient/blob/bug/ack_on_persistent_subscription/tests/test_persistent_subscription.py#L79) tests that replicate this scenario.

Is this a valid assumption, or I assume the wrong behavior?

**Comment by johnbywater** [comment]
Hi @lzukowski, thanks for raising this issue. Sorry for the delay in replying. I have just been away on an extended summer break.

I'm a little bit unsure about the correct answer to your question. But yes, the general idea with persistent subscriptions is that ACKed events aren't received again. But the persistent subscription behaviour seems to be somewhat indeterministic with respect to the order and the uniqueness of delivery, especially compared with catchup subscriptions which is quite solid. It might be that the server is retrying to send the event because it wasn't ACKed quickly enough. I think, basically, there aren't really solid guarantees and persistent subscription consumers need to be coded to take responsibility for these aspects. For these reasons the catch up subscription is really the preferred way of processing recorded events, with the much more complicated persistent subscription feature having been added later to support use cases that are more "relaxed" about the results.

I will ask the Event Store DB team about this issue. I'm working under their guidance, and my comments above reflect what I've been told by them previously.

Again, thanks for raising this issue, and sorry for the delay in responding. I was just on holiday.

**Comment by johnbywater** [comment]
There was a bug in the client code. Which I fixed in your PR #7, see https://github.com/pyeventsourcing/esdbclient/pull/7#issuecomment-1760076472 for details. Many thanks for raising this issue, expressing the concern as a nice test, and again I'm sorry for the delay in responding.

**Comment by lzukowski** [comment]
When I run tests locally it still is not passing. I'm not sure if it's issue of osX (arm CPU) that I'm running this tests on or still something is wrong.

**Comment by johnbywater** [comment]
Which version are you using? Please use the 1.0 branch.

There's now a "grace" argument to the read subscription functions. This controls how much time we are giving the server to record the ACK before shutting down the gRPC streams. Maybe try using a larger value?

If this still doesn't work, we will need to investigate further :)

**Comment by lzukowski** [comment]
My bad, new 1.0b2 is working :+1:
Thx.

**Comment by johnbywater** [comment]
Great news! Thanks for letting us know.
